<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDC3-L-128FX5H" ignored="0" name="Regressioin1" tests="5" failures="2" timestamp="2021-09-20T14:22:18 IST" time="2.838" errors="0">
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.851" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="expected [401] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [200]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:46)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.851" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="expected [401] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [401] but found [200]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:46)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.61" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.719" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.818" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
</testsuite> <!-- Regressioin1 -->
