<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HDC3-L-128FX5H" name="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest" tests="5" failures="2" timestamp="2021-09-23T17:20:16 IST" time="8.118" errors="0">
  <testcase name="inValidingCustomerWithValidSecrectkey" time="2.089" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTableTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <system-out/>
  <testcase name="inValidingCustomerWithValidSecrectkey" time="2.089" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTableTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <system-out/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.275" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest"/>
  <system-out/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.361" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest"/>
  <system-out/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="1.304" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest"/>
  <system-out/>
</testsuite> <!-- com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTableTest -->
